#! /bin/sh
sxhkd &
libinput-gestures-setup restart &

bspc monitor eDP1 -d 4 5 6 0
bspc monitor DP1  -d 1 2 3 7 8 9

bspc config border_width              1
bspc config window_gap                10
bspc config top_padding               25

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config paddingless_monocle       false
bspc config focus_follows_pointer     true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc rule -a XTerm:FloatingTerminal state=floating
bspc rule -a XTerm:FloatingVim state=floating
bspc rule -a Chromium desktop="^3" follow=off
bspc rule -a TelegramDesktop desktop="^4"
bspc rule -a Calculator state=floating

polybar main --reload &
polybar second --reload &
