#! /bin/sh
bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width              2
bspc config window_gap                6
bspc config top_padding               40

bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config paddingless_monocle       false
bspc config focus_follows_pointer     true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config focused_border_color      '#3FC1B0'

bspc rule -a Alacritty:FloatingTerminal state=floating
bspc rule -a XTerm:FloatingVim state=floating
bspc rule -a Google-chrome desktop="^3" follow=off
bspc rule -a TelegramDesktop desktop="^4"
bspc rule -a zoom desktop="^9"
bspc rule -a Calculator state=floating
bspc rule -a Blueman-manager state=floating center=true rectangle=592x500+0+0
bspc rule -a feh state=floating

sxhkd &
picom &
polybar main &
feh --bg-fill /home/serezha/Pictures/wallpapers/wall49.jpg &
xsetroot -cursor_name left_ptr &
